[package]
name = "rcsj_solver"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module", "abi3-py38"] }
physical_constants = "0.5.0"
ndarray = "0.16"
numpy = "0.27"

[lib]
name = "rcsj_solver"
crate-type = ["cdylib"]